### ISSUE TITLE
No ipv6 on Hetzner cloud

### ISSUE THREAD

**Issue by bramd** [elitak/nixos-infect#106]
After running nix-infect on a clean Hetzner Cloud VPS, the system comes back after reboot and works fine, except ipv6.

It seems the ipv4 address is provided through DHCP, but ipv6 is static. It would be nice if there is an option to only generate an ipv6 network configuration.

**Comment by bramd** [comment]
For people who want to get this to work:

1. Set the environment variable `doNetConf=y` to generate network configuration
2. Add this to your configuration: `networking.defaultGateway6.interface = "eth0";`. This is needed because the gateway will be `fe80::1` and this does not work with an interface specification

**Comment by sovanix** [comment]
@bramd if this is still an issue would you create pr with a note under `hetzner`?
