### ISSUE TITLE
OCI Oracle7.9 used to work

### ISSUE THREAD

**Issue by keithy** [elitak/nixos-infect#114]
Now hangs at "Welcome to Grub2"

only obvious error
```
+/nix/var/nix/profiles/system/bin/switch-to-configuration boot
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
    LANGUAGE = (unset),
    LC_ALL = (unset),
    LANG = "en_GB.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
```

Ubuntu 20.04-slim worked
Ubuntu 22.04-slim worked

**Comment by s-o-v-a** [comment]
@keithy it appears to be possible environment variable not being set right.  are you able to run testing on nixos-infect by passing the newer channel `22.11` ?

**Comment by keithy** [comment]
Oracle8 worked with 22.11
