### ISSUE TITLE
Hetzner Cloud - user data vs. curl nixos-infect

### ISSUE THREAD

**Issue by Bouni** [elitak/nixos-infect#139]
The wiki says that I have to run `nixos-infect`on a debian or ubuntu but the README says `Hetzner cloud works out of the box. When creating a server provide the following script as "User data"`
But I cannot find a `user data` field when adding a server.
Is the README outdated is it me that is to stupid to find that `user data` 😅 ?

**Comment by eboskma** [comment]
I just created a server on Hetzner cloud, they use cloud-config now. I just copied the snippet from the DigitalOcean instructions, pasted it in the Cloud Config field and changed the `PROVIDER` to `hetznercloud`

**Comment by Bouni** [comment]
Nice, that's for that tip 👍
