### ISSUE TITLE
The authorized-keys migrator does not correctly handle sk-variant ssh keys

### ISSUE THREAD

**Issue by anoadragon453** [elitak/nixos-infect#160]
Running nixos-infect, I found that one of my two entries from `/root/.ssh/authorized-keys` was not copied correctly. The unhandled entry was:

```
sk-ssh-ed25519@openssh.com AAAA...
```

However, what ended up in my `/etc/nixos/configuration.nix` file was:

```
  users.users.root.openssh.authorizedKeys.keys = [
    ''ssh-ed25519@openssh.com AAAA..."
  ];
```

whereas the entry should have been ''sk-ssh-ed25519@openssh.com AAAA..." (note the new `sk-`).

A minor difference, but prevents ssh login from functioning. I ended up using my other ssh key to get in.

---

The relevant portion of the code to fix appears to be:

https://github.com/elitak/nixos-infect/blob/c9419eb629f03b7abcc0322340b6aaefb4eb2b60/nixos-infect#L21-L26

**Comment by thegleich** [comment]
I've encountered the same issue.
