### ISSUE TITLE
networking.interfaces.<name?>.ipv4.addresses won't let build to finish

### ISSUE THREAD

**Issue by ivanovsaleksejs** [elitak/nixos-infect#23]
networking.interfaces.<name?>.ipv4.addresses option in /etc/nixos/networking.nix will trigger an error and won't let initial build to finish. According to https://nixos.org/nixos/options.html#ip4 it should be networking.interfaces.<name?>.ipv4. I manually edited that file by removing ".addresses" and was able to complete the build.

DigitalOcean, Ubuntu16.04.

**Comment by elitak** [comment]
This has changed for release 18.03. See https://nixos.org/nixos/manual/release-notes.html#sec-release-18.03-notable-changes

Either use v18.03+ or revert the two related commits in the recent history. The README.md is still suggesting 17.09, so I'll fix that.

**Comment by elitak** [comment]
I still had an old default in there, so I updated it. The script should run without issue now.
