### ISSUE TITLE
Hostsailor: unable to set password

### ISSUE THREAD

**Issue by Th0rgal** [elitak/nixos-infect#41]
Hello,

I just installed nixos using nixosinfect but I have a problem: now when I start my vps it asks me to login but my old credentials are no longer working and I don't know the new ones. I tried to change the password using systemd.debug-shell but I can't get to tty9 using VNC.
How should I do?

Thank you very much,
Thomas

**Comment by elitak** [comment]
Append `init=/bin/sh` to the kernel boot params, then use `passwd` to set the root password.
