### ISSUE TITLE
installation fails because of script inside `authorized_keys`

### ISSUE THREAD

**Issue by DavHau** [elitak/nixos-infect#43]
It seemed a bit crazy to me, but actually it is part of the cloudinit standard to put scripts inside `/root/authorized_keys` to prevent direct root login for example and return a message to the user who tried. 

A typical cloud init generated `authrized_keys` can look like that:
```
no-port-forwarding,no-agent-forwarding,no-X11-forwarding,command="echo 'Please login as the user \"ubuntu\" rather than the user \"root\".';echo;sleep 10" ssh-ed25519 AAAAdeadbeefxxxxxxxxxx.......
```
Since nixos-infect copies all of that into `users.users.root.openssh.authorizedKeys.keys`, the nixos installation fails. I'm not sure what would be the best way to modify the current regex to capture that case. I would appreciate some help with the grep magic.

**Comment by elitak** [comment]
I haven't tested it beyond the regex, but something like this should store the sanitized lines into the `keys` var:
```
for trypath in /root/authorized_keys /root/.ssh/authorized_keys; do [[ -r "$trypath" ]] && keys=$(sed -E 's/.*(ssh-[^[:space:]]+)[[:space:]]+([[:alnum:]]+)[[:space:]]*.*/\1 \2/') && break; done
```

**Comment by grische** [comment]
@elitak I think you forgot the `$trypath` inside the subshell for this to work

@DavHau if you to improve upon it, a few suggestions:
```
AUTHORIZED_KEYS FILE FORMAT
     AuthorizedKeysFile specifies the files containing public keys for public
     key authentication; if this option is not specified, the default is
     ~/.ssh/authorized_keys and ~/.ssh/authorized_keys2.  Each line of the file
     contains one key (empty lines and lines starting with a ‘#’ are ignored as
     comments).  Public keys consist of the following space-separated fields:
     options, keytype, base64-encoded key, comment.  The options field is
     optional.  The keytype is “ecdsa-sha2-nistp256”, “ecdsa-sha2-nistp384”,
     “ecdsa-sha2-nistp521”, “ssh-ed25519”, “ssh-dss” or “ssh-rsa”; the comment
     field is not used for anything (but may be convenient for the user to
     identify the key).
```
* allow `ecdsa-...` as well as of `ssh-...`
* keep the ssh comment field

This should probably work for you:
```
for trypath in /root/authorized_keys /root/.ssh/authorized_keys; do [[ -r "$trypath" ]] && keys=$(sed -E 's/^.*((ssh|ecdsa)-[^[:space:]]+)[[:space:]]+([^[:space:]]+)([[:space:]]*.*)$/\1 \3\4/' "$trypath") && break; done
```

**Comment by elitak** [comment]
Yeah, I did forget `$trypath`, thanks.

Probably all the possible locations should be `cat`ed together, including `authorized_keys2`.

The options field is allowed to be quoted, to escape the space delimiters. I didn't handle that, but now that I think about it, using `set -- $line` from bash would be a better way to handle any nested quotes/escape sequences, that way we don't have to match on `(ssh|ecdsa|something-from-the-future)-`.

Something like this (untested):
```
local -a keys
(cat /root/{,.ssh/}authorized_keys{,2} || true) | while read line; do
  set -- $line
  [[ "$#" -eq 4 ]] && shift
  keys+=("$@")
done
# later use "${keys[@]}" to include into .nix
```

**Comment by grische** [comment]
@elitak if you are not bound by using a one line, I would write some proper bash code.

For instance I would suggest to simply loop over a list of files and parse them without using any cat at all.
Then parsing the files with a nice function.

I don't see a reason not to use the regex, if the specification says those key prefixes are fixed anyway.

At first sight it also seems that your code doesn't handle that both the options field as well as the comment field of the authorized_keys file are optional.
