### ISSUE TITLE
Hetzner: manual nameserver config not needed

### ISSUE THREAD

**Issue by DavHau** [elitak/nixos-infect#48]
I just tried the infect script on a hetzner cloud VM. When i set `PROVIDER` to something else than `digitalocean`, the installation just works fine and also afterwards dns resolution works without problems.
Maye the readme should be changed to use `PROVIDER=hetznercloud` instead of `digitalocean` and the nameserver hack can be removed.

**Comment by obadz** [comment]
Cc @chrissound who authored the Hetzner support (#47)

**Comment by chrissound** [comment]
I'm not too familiar with this, but I assume the PROVIDER is just an override so it could possibly just be left out entirely.

As for the nameserver hack not being needed - what was the starting distro you used? @DavHau maybe it's only needed for Ubuntu.

**Comment by DavHau** [comment]
I'm using it on ubuntu (both 16.04 and 18.04). It works fine without any extra config as soon as you set PROVIDER to anything else than digitalocean.

PROVIDER=digitalocean runs a special routine which adds some custom network stuff. 
On all hosters I've tried so far, this is not required and instead just breaks things like dns.

This is why I also think that the default value for provider should not be digitalocean. see https://github.com/elitak/nixos-infect/issues/49
It just makes things for difficult in most of the cases and confuses people.

**Comment by jwoudenberg** [comment]
I can confirm that without the `PROVIDER` and `NIXOS_IMPORT` flags specified the `nixos-infect` script by itself works on hetzner cloud. I've tried with Ubuntu 20.04 as a starting distro.

**Comment by chrissound** [comment]
This makes sense to me. And I agree with your PR. :)
