### ISSUE TITLE
ssh on complete not authorized

### ISSUE THREAD

**Issue by naglalakk** [elitak/nixos-infect#50]
I've skimmed through the script and it seems to me that it's preserving keys located in ~/.ssh/authorized_keys. I have my key in there for root but when I install nixOS with this script I cannot ssh back into it once the script is complete and the machine has performed a reboot. 
I'm currently running this script as root user. Is there any additional config I need to add in order for this to work?

**Comment by elitak** [comment]
It should work by default, but then the ssh-key-handling code did change recently. Comment out the `reboot` from the script, run it as normal, then inspect `/etc/nixos/configuration.nix` to see if the authorized_keys were handled properly.

**Comment by naglalakk** [comment]
It does indeed handle this properly. It was my own fault. After reboot you simply have to clear the key that is already present in ~/.ssh/known_hosts so it adds it again, the correct one. 
Closing this issue now. The code is doing this correctly.
