### ISSUE TITLE
Multiple interfaces create invalid IP config

### ISSUE THREAD

**Issue by peterhoeg** [elitak/nixos-infect#7]
If you create a digital ocean VM with 2 interfaces (one public and one private), the configuration by nixos-infect is as follows:

``` nix
interfaces = {
  eth0 = {
    ip4 = [
      { address="1.2.3.4"; prefixLength=18; }
      { address="10.15.0.8"; prefixLength=16; }
    ];
  };
  # eth1 is for private networking or something?
  eth1.useDHCP = false;
};
```

It should instead be:

``` nix
interfaces = {
  eth0 = {
    ip4 = [
      { address="1.2.3.4"; prefixLength=18; }
    ];
  };
  eth1 = {
    ip4 = [
      { address="10.15.0.8"; prefixLength=16; }
    ];
  };
};
```

**Comment by elitak** [comment]
I created a droplet with private networking to test this, but in my case, I ended up with 1 10.x address for each interface. Can you verify the issue's been resolved?

**Comment by peterhoeg** [comment]
@elitak, I haven't had the time to test it out, but I will over the weekend and then let you know.
